# Site settings
title: Personal blog Vinicio Henrique
description: Personal blog Vinicio Henrique
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://viniciotricolor.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vinicio Henrique
user_description: olá
user_title: Software Developer
email: viniciotricolor@pm.me
twitter_username: viniciotricolor
github_username:  viniciotricolor
gplus_username:  viniciotricolor

# Google-analytics
google-analytics:
  id: "UA-128946895-1"

exclude: ['package.json', 'src' , 'node_modules']
